#stages:
#  - test
#  - deploy

variables:
  GIT_SSL_NO_VERIFY: "true"

test:
  image: hemtt/hemtt:master
  allow_failure: false
#  stage: test
  before_script:
    - hemtt --version
  script:
    - make test
  only:
    - master

deploy:
  image: hemtt/hemtt:master
  allow_failure: false
#  stage: deploy
  before_script:
    - hemtt --version
  script:
    - hemtt build
